[package]
name = "json-benchmark"
version = "0.0.1"
authors = ["dtolnay@gmail.com"]
edition = "2018"
publish = false

[dependencies]
getopts = "0.2"
json = { version = "0.11", optional = true }
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde-bench = { version = "0.0.7", optional = true }
serde_json = { version = "1.0", optional = true }
simd-json = { version = "0.3", optional = true, path = "../simd-json"}
time = "0.1"
jemallocator = "0.3"
mimalloc = { version = "*", default-features = false }
snmalloc-rs = "0.2.3"
simd-json-derive = { version = "0.1", optional = true, path = "../simd-json-derive"}


[features]
default = ["performance", "all-libs", "all-files"]
all-libs = ["lib-serde", "lib-simd-json", "lib-simd-json-tape"]
#all-libs = ["lib-serde", "lib-json-rust", "lib-simd-json", "lib-simd-json-tape"]
all-files = ["file-canada", "file-citm-catalog", "file-twitter", "file-log", "file-apache-builds"]
performance = ["parse-dom", "stringify-dom", "parse-struct", "stringify-struct"]
lib-serde = ["serde", "serde_json"]
lib-simd-json = ["simd-json", "serde", "simd-json-derive"]
lib-simd-json-tape = ["simd-json"]
lib-json-rust = ["json"]
lib-rustc-serialize = ["rustc-serialize"]
file-canada = []
file-citm-catalog = []
file-twitter = []
file-log = []
file-apache-builds = []
parse-dom = []
stringify-dom = []
parse-struct = []
stringify-struct = []
zero-copy = []
binary = ["serde-bench", "lib-serde"]

[profile.release]
debug = true
panic = "abort"

[workspace]
members = ["binary"]
# [patch.crates-io]
# value-trait = { path = '../value-trait' }

